#!/usr/bin/env python3
"""Generate SUMMARY.md — the Phase 2 one-page review of all extracted years.
Run after extract.py:  python3 scripts/summary.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
data = json.loads((ROOT / "data" / "hhga.json").read_text())
players = {p["id"]: p["name"] for p in data["players"]}

lines = [
    "# HHGA 2000-2025 — Phase 2 Review Summary",
    "",
    "All champions verified by Ryan (2026-07-02 / 2026-07-04). "
    "Generated by scripts/summary.py from data/hhga.json.",
    "",
    "| Year | Location | Courses | Players | Champion | Net | Mist-Weed |",
    "|------|----------|---------|---------|----------|-----|-----------|",
]

for yr in data["years"]:
    champ = players[yr["champion"]] if yr.get("champion") else "— (washout)"
    lb = yr["leaderboard"][0] if yr["leaderboard"] else None
    score = (lb.get("net", lb.get("gross")) if lb else None)
    mw = ""
    mwd = yr.get("sideGames", {}).get("mistWeed")
    if mwd and mwd.get("final"):
        f = mwd["final"]
        mw = f"{mwd['winner'].title()} {f['mist']:g}-{f['weed']:g}"
    courses = ", ".join(yr["courses"])
    n = len(yr["leaderboard"]) or len(yr.get("attendees", []))
    scoring = " (gross)" if yr.get("scoring") == "gross" else ""
    score_s = f"{score:g}{scoring}" if score is not None else "—"
    lines.append(
        f"| {yr['year']} | {yr['location']} | {courses} | {n} "
        f"| **{champ}** | {score_s} | {mw} |")

lines += [
    "",
    "## Titles",
    "",
]
titles = {}
for yr in data["years"]:
    if yr.get("champion"):
        titles[yr["champion"]] = titles.get(yr["champion"], 0) + 1
for pid, n in sorted(titles.items(), key=lambda kv: -kv[1]):
    lines.append(f"- {players[pid]}: {n}")

lines += [
    "",
    "## Open items (non-blocking, for Ryan whenever)",
    "",
    "- Real/full names: Irv, Craig ('Knees'), Billy ('Brother Billy'), Jeff, "
    "Troy, Jimmy B, Matt, Loyd, T-Dog Hitman, Cookie AC Milan, Big Gay Al "
    "(2005 stand-in), Scotty H (2025 — attended? scored?).",
    "- 2025: Year in Review says Greg's and Jimmy's scores weren't recorded — "
    "confirm who attended.",
    "- 2008 Myrtle Cup final result unknown (doc ends 4.5-4.5 before Thursday "
    "singles).",
    "- Pre-2024 champion 'format' history unclear (2024 'trial format' = "
    "cumulative net over 4 days per Ryan; data suggests cumulative net was "
    "the metric all along).",
]

out = ROOT / "SUMMARY.md"
out.write_text("\n".join(lines) + "\n")
print(f"Wrote {out}")
